### ISSUE TITLE
DEPRECATION glimmer.private-in-element

### ISSUE THREAD

**Issue by VincentMolinie** [ember-polyfills/ember-in-element-polyfill#189]
It looks like you are transforming all `in-element` to `-in-element` what about ember versions that has the native `in-element` ? 
I get the following error when starting my app:
![Capture d’écran 2020-12-28 à 15 19 20](https://user-images.githubusercontent.com/3263749/103220326-4d530680-4920-11eb-90e9-681c8af1e280.png)

I'm using `Ember 3.20` and `ember-leaflet:4.1.1` which use your library internally

**Comment by simonihmig** [comment]
In that case it should actually do nothing (as per #81). But I also see deprecation warnings in CI for latest Ember. So something seems off indeed... thanks for reporting!

**Comment by simonihmig** [comment]
I think I misinterpreted the deprecation in our own CI logs. This comes from some tests which specifically test for `-in-element` usage.

Your screenshot shows that an outdated version of `ember-composability-tools` is used, which most likely does not use the latest (1.0.0) version of ember-in-element-polyfill. I would recommend to make sure you don't use any version prior to that (e.g. `yarn why ember-in-element-polyfill`), by updating all addons or using something like yarn's `resolutions` (assuming you use yarn).

Closing this, as I believe the latest version of this polyfill should be fine. Feel free to reopen if you have prove that this is not the case!
