### ISSUE TITLE
Deprecation warning under ember 3.28.x

### ISSUE THREAD

**Issue by spuxx1701** [ember-polyfills/ember-in-element-polyfill#294]
ember-in-element-polyfill@1.0.1 seems to cause deprecation warnings under ember 3.28.x.

Deprecation id: `template-compiler.registerPlugin`
https://deprecations.emberjs.com/v3.x/#toc_template-compiler-registerPlugin

```
"ember-source": "^3.28.8"
"ember-cli": "^3.28.4"
```

**Comment by cah-briangantzler** [comment]
Is it because it in not becoming inert for the versions of ember that do not need it?

Would like to get this noise removed from my builds. :)
