### ISSUE TITLE
Thoughts on moving into ember-polyfills org?

### ISSUE THREAD

**Issue by rwjblue** [ember-polyfills/ember-in-element-polyfill#84]
I've made an [ember-polyfills](https://github.com/ember-polyfills) org and moved all of the polyfills I've written into it. The idea is roughly to increase bus factor while also increasing discoverability.

What do you think about moving this repo into that org? I'll happily add you as an owner there...

**Comment by simonihmig** [comment]
@rwjblue I am fine with that. Given that it was mostly developed on company-time, I would like to put a short copyright/credit notice into the Readme if that's ok. Will move the repo then the next days, currently a bit buried with work...

**Comment by rwjblue** [comment]
> Given that it was mostly developed on company-time, I would like to put a short copyright/credit notice into the Readme if that's ok.

Ya, absolutely!! FWIW, the goal here is certainly not to reduce recognition for peoples hard work (company sponsored or personal), and a very loud shoutout in the README to the original author seems like a great start (though I wonder what else we could do :thinking:).

**Comment by simonihmig** [comment]
Done! Will update the repo URLs etc. shortly.

@rwjblue What about npm access, should I add you *personally*, anyone else, or is this managed through an org?

**Comment by rwjblue** [comment]
@simonihmig - Ya, if you can add me for now that would be great. I'll create an org shortly so that we can more easily manage the other packages too (part of the increased bus factor objective).

**Comment by simonihmig** [comment]
Done!
